apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images: null

commonLabels:
  app.kubernetes.io/name: bomc-ms
  
resources:
- 010-argocd-project.yaml
- 020-argocd-con-application.yaml
- 030-argocd-pub-application.yaml
