apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ./000-argocd-namespace.yaml
- ./010-argocd-install-2.0.0.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-server
  path: ./patches/argocd-insecure-rootpath-patch.yaml
- target:
    version: v1
    kind: Service
    name: argocd-server
  path: ./patches/argocd-ambassador-service-patch.yaml

